[package]
name = "seq_io"
version = "0.4.0-alpha.0"
authors = ["<markschl19@gmail.com>"]
description = "Fast FASTA, FASTQ and FASTX parsing and writing"
license = "MIT"
repository = "https://github.com/markschl/seq_io"
documentation = "https://docs.rs/seq_io"
readme = "README.md"
keywords = ["bio", "fasta", "fastq", "parser"]
exclude = [
    "bench_results/*",
]
edition = "2018"

[features]
strict_length_check = []

[dependencies]
memchr = "2.3"
buf_redux = { version = "0.8", default_features = false }
scoped_threadpool ="0.1"
crossbeam = "0.8"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
bio = "0.32"
fastq = "0.6"
matches = "^0.1.8"
lazy_static = "1.4"
rand = "0.7"
rand_isaac = "0.2"
rand_distr = "0.2"
criterion = { version = "0.3", default_features = false }

[profile.bench]
lto = true
codegen-units = 1

[[bench]]
name = "fasta"
harness = false

[[bench]]
name = "fastq"
harness = false
